version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clevertec-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - backend
  db:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: clevertec-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - backend

networks:
  backend: