spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway.enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate.search.backend:
        lucene_version: 'LATEST'
        directory.root: './temp/lucene/indices'