CREATE TABLE discount_cards
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    discount   DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_discount_cards PRIMARY KEY (id)
);

CREATE TABLE positions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INTEGER                                 NOT NULL,
    total      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_positions PRIMARY KEY (id)
);

CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    price       DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE receipt_positions
(
    receipt_id   BIGINT NOT NULL,
    positions_id BIGINT NOT NULL,
    CONSTRAINT pk_receipt_positions PRIMARY KEY (receipt_id, positions_id)
);

CREATE TABLE receipts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description      VARCHAR(255)                            NOT NULL,
    discount_card_id BIGINT,
    total            DOUBLE PRECISION                        NOT NULL,
    discount         DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_receipts PRIMARY KEY (id)
);

ALTER TABLE receipt_positions
    ADD CONSTRAINT uc_receipt_positions_positions UNIQUE (positions_id);

ALTER TABLE positions
    ADD CONSTRAINT FK_POSITIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE receipts
    ADD CONSTRAINT FK_RECEIPTS_ON_DISCOUNTCARD FOREIGN KEY (discount_card_id) REFERENCES discount_cards (id);

ALTER TABLE receipt_positions
    ADD CONSTRAINT fk_recpos_on_receipt FOREIGN KEY (receipt_id) REFERENCES receipts (id);

ALTER TABLE receipt_positions
    ADD CONSTRAINT fk_recpos_on_receipt_position FOREIGN KEY (positions_id) REFERENCES positions (id);